export const SET_COMMON_USER_ERROR = 'SET_COMMON_ERROR'

export const STORE_COMMON_USER = 'STORE_COMMON_USER';


export const STORE_COMMON_BIDDER = 'STORE_COMMON_BID';

export const COMMON_INDICATOR = 'COMMON_INDICATOR';