/**
 * STATISTICS ACTIONS
 * These actions are for STATISTICs
*/
export const SET_STATISTIC_ERROR = 'SET_STATISTIC_ERROR'

export const ADD_STATISTIC_BEGIN = 'ADD_STATISTIC_BEGIN';
export const ADD_STATISTIC_SUCCESS = 'ADD_STATISTIC_SUCCESS';

export const EDIT_STATISTIC_BEGIN = 'EDIT_STATISTIC_BEGIN';
export const EDIT_STATISTIC_SUCCESS = 'EDIT_STATISTIC_SUCCESS';

export const GET_STATISTIC_BEGIN = 'GET_STATISTIC_BEGIN';
export const GET_STATISTIC_SUCCESS = 'GET_STATISTIC_SUCCESS';

export const GET_STATISTICS_BEGIN = 'GET_STATISTICS_BEGIN';
export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';

export const GET_MORE_STATISTICS_BEGIN = 'GET_MORE_STATISTICS_BEGIN';
export const GET_MORE_STATISTICS_SUCCESS = 'GET_MORE_STATISTICS_SUCCESS';

export const DELETE_STATISTIC_BEGIN = 'DELETE_STATISTIC_BEGIN';
export const DELETE_STATISTIC_SUCCESS = 'DELETE_STATISTIC_SUCCESS';